// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtseEaraYByI3KFGXWdFZy0Di5P7kzp3M',
    appId: '1:120839154227:web:d2244402f55e5a23841146',
    messagingSenderId: '120839154227',
    projectId: 'bulk-pal',
    authDomain: 'bulk-pal.firebaseapp.com',
    storageBucket: 'bulk-pal.firebasestorage.app',
    measurementId: 'G-7JDXPPS057',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKNlo6NV-soUS4x7pN-UZANK8A_l3MVY',
    appId: '1:120839154227:android:ccd78c6c24988409841146',
    messagingSenderId: '120839154227',
    projectId: 'bulk-pal',
    storageBucket: 'bulk-pal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx9Xb9Xs6uEgVZpoDycSe2Jzb8kA1_OQc',
    appId: '1:120839154227:ios:363195b79d1513dd841146',
    messagingSenderId: '120839154227',
    projectId: 'bulk-pal',
    storageBucket: 'bulk-pal.firebasestorage.app',
    iosBundleId: 'com.example.bulkpalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx9Xb9Xs6uEgVZpoDycSe2Jzb8kA1_OQc',
    appId: '1:120839154227:ios:363195b79d1513dd841146',
    messagingSenderId: '120839154227',
    projectId: 'bulk-pal',
    storageBucket: 'bulk-pal.firebasestorage.app',
    iosBundleId: 'com.example.bulkpalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtseEaraYByI3KFGXWdFZy0Di5P7kzp3M',
    appId: '1:120839154227:web:428b638fc394d921841146',
    messagingSenderId: '120839154227',
    projectId: 'bulk-pal',
    authDomain: 'bulk-pal.firebaseapp.com',
    storageBucket: 'bulk-pal.firebasestorage.app',
    measurementId: 'G-YRDGXMYLXC',
  );
}
